# coding: utf-8

"""
    Runai API

    # Introduction  The Run:AI Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create an **Application** through the Run:ai user interface. To create an application, in your UI, go to `Settings & Tools`, `Application` and create a new Application.  After you have created a new application, you will need to assign it access rules. To assign access rules to the application, see [Create access rules](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#create-or-delete-rules). Make sure you assign the correct rules to your application. Use the [Roles](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://docs.run.ai/latest/developer/rest-auth/#request-an-api-token).   # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.jobs_api import JobsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self):
        self.api = JobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cluster_jobs_count(self):
        """Test case for get_cluster_jobs_count

        Return the number all Jobs in the cluster. Deprecated - please use api/v1/workloads/count instead  # noqa: E501
        """
        pass

    def test_get_pods_by_job_id(self):
        """Test case for get_pods_by_job_id

        Get all pods that are associated for a specific job. Deprecated - please use api/v1/workloads/{workloadId}/pods instead  # noqa: E501
        """
        pass

    def test_list_jobs(self):
        """Test case for list_jobs

        List all Jobs in the cluster. Deprecated - please use api/v1/workloads instead  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
