# coding: utf-8

"""
    Runai API

    # Introduction  The Run:AI Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create an **Application** through the Run:ai user interface. To create an application, in your UI, go to `Settings & Tools`, `Application` and create a new Application.  After you have created a new application, you will need to assign it access rules. To assign access rules to the application, see [Create access rules](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#create-or-delete-rules). Make sure you assign the correct rules to your application. Use the [Roles](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://docs.run.ai/latest/developer/rest-auth/#request-an-api-token).   # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.auto_scaling_common_fields import AutoScalingCommonFields  # noqa: F401,E501

class AllOfSpecificRunAutoScalingAutoScaling(AutoScalingCommonFields):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'threshold_metric': 'AutoScalingMetric',
        'threshold_value': 'int'
    }
    if hasattr(AutoScalingCommonFields, "swagger_types"):
        swagger_types.update(AutoScalingCommonFields.swagger_types)

    attribute_map = {
        'threshold_metric': 'thresholdMetric',
        'threshold_value': 'thresholdValue'
    }
    if hasattr(AutoScalingCommonFields, "attribute_map"):
        attribute_map.update(AutoScalingCommonFields.attribute_map)

    def __init__(self, threshold_metric=None, threshold_value=None, *args, **kwargs):  # noqa: E501
        """AllOfSpecificRunAutoScalingAutoScaling - a model defined in Swagger"""  # noqa: E501
        self._threshold_metric = None
        self._threshold_value = None
        self.discriminator = None
        if threshold_metric is not None:
            self.threshold_metric = threshold_metric
        if threshold_value is not None:
            self.threshold_value = threshold_value
        AutoScalingCommonFields.__init__(self, *args, **kwargs)

    @property
    def threshold_metric(self):
        """Gets the threshold_metric of this AllOfSpecificRunAutoScalingAutoScaling.  # noqa: E501


        :return: The threshold_metric of this AllOfSpecificRunAutoScalingAutoScaling.  # noqa: E501
        :rtype: AutoScalingMetric
        """
        return self._threshold_metric

    @threshold_metric.setter
    def threshold_metric(self, threshold_metric):
        """Sets the threshold_metric of this AllOfSpecificRunAutoScalingAutoScaling.


        :param threshold_metric: The threshold_metric of this AllOfSpecificRunAutoScalingAutoScaling.  # noqa: E501
        :type: AutoScalingMetric
        """

        self._threshold_metric = threshold_metric

    @property
    def threshold_value(self):
        """Gets the threshold_value of this AllOfSpecificRunAutoScalingAutoScaling.  # noqa: E501

        The threshold value to use with the specified metric for autoscaling  # noqa: E501

        :return: The threshold_value of this AllOfSpecificRunAutoScalingAutoScaling.  # noqa: E501
        :rtype: int
        """
        return self._threshold_value

    @threshold_value.setter
    def threshold_value(self, threshold_value):
        """Sets the threshold_value of this AllOfSpecificRunAutoScalingAutoScaling.

        The threshold value to use with the specified metric for autoscaling  # noqa: E501

        :param threshold_value: The threshold_value of this AllOfSpecificRunAutoScalingAutoScaling.  # noqa: E501
        :type: int
        """

        self._threshold_value = threshold_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AllOfSpecificRunAutoScalingAutoScaling, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AllOfSpecificRunAutoScalingAutoScaling):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
