# coding: utf-8

"""
    Runai API

    # Introduction  The Run:AI Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create an **Application** through the Run:ai user interface. To create an application, in your UI, go to `Settings & Tools`, `Application` and create a new Application.  After you have created a new application, you will need to assign it access rules. To assign access rules to the application, see [Create access rules](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#create-or-delete-rules). Make sure you assign the correct rules to your application. Use the [Roles](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://docs.run.ai/latest/developer/rest-auth/#request-an-api-token).   # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComplianceInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'imposed': 'bool',
        'compliance': 'bool',
        'reason': 'list[ComplianceInfoReason]'
    }

    attribute_map = {
        'imposed': 'imposed',
        'compliance': 'compliance',
        'reason': 'reason'
    }

    def __init__(self, imposed=None, compliance=None, reason=None):  # noqa: E501
        """ComplianceInfo - a model defined in Swagger"""  # noqa: E501
        self._imposed = None
        self._compliance = None
        self._reason = None
        self.discriminator = None
        if imposed is not None:
            self.imposed = imposed
        if compliance is not None:
            self.compliance = compliance
        if reason is not None:
            self.reason = reason

    @property
    def imposed(self):
        """Gets the imposed of this ComplianceInfo.  # noqa: E501

        Whether the asset is imposed on created workloads by the administrator.  # noqa: E501

        :return: The imposed of this ComplianceInfo.  # noqa: E501
        :rtype: bool
        """
        return self._imposed

    @imposed.setter
    def imposed(self, imposed):
        """Sets the imposed of this ComplianceInfo.

        Whether the asset is imposed on created workloads by the administrator.  # noqa: E501

        :param imposed: The imposed of this ComplianceInfo.  # noqa: E501
        :type: bool
        """

        self._imposed = imposed

    @property
    def compliance(self):
        """Gets the compliance of this ComplianceInfo.  # noqa: E501

        Whether the asset info complies with creation of workloads in the project.  # noqa: E501

        :return: The compliance of this ComplianceInfo.  # noqa: E501
        :rtype: bool
        """
        return self._compliance

    @compliance.setter
    def compliance(self, compliance):
        """Sets the compliance of this ComplianceInfo.

        Whether the asset info complies with creation of workloads in the project.  # noqa: E501

        :param compliance: The compliance of this ComplianceInfo.  # noqa: E501
        :type: bool
        """

        self._compliance = compliance

    @property
    def reason(self):
        """Gets the reason of this ComplianceInfo.  # noqa: E501

        For asset that does not comply, specify one or more reason why.  # noqa: E501

        :return: The reason of this ComplianceInfo.  # noqa: E501
        :rtype: list[ComplianceInfoReason]
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this ComplianceInfo.

        For asset that does not comply, specify one or more reason why.  # noqa: E501

        :param reason: The reason of this ComplianceInfo.  # noqa: E501
        :type: list[ComplianceInfoReason]
        """

        self._reason = reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComplianceInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComplianceInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
