# coding: utf-8

"""
    Runai API

    # Introduction  The Run:AI Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create an **Application** through the Run:ai user interface. To create an application, in your UI, go to `Settings & Tools`, `Application` and create a new Application.  After you have created a new application, you will need to assign it access rules. To assign access rules to the application, see [Create access rules](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#create-or-delete-rules). Make sure you assign the correct rules to your application. Use the [Roles](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://docs.run.ai/latest/developer/rest-auth/#request-an-api-token).   # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.datavolume_inner_fields import DatavolumeInnerFields  # noqa: F401,E501

class DatavolumeInternal(DatavolumeInnerFields):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'shared_scopes': 'list[SharedScope]',
        'phase': 'DatavolumePhase'
    }
    if hasattr(DatavolumeInnerFields, "swagger_types"):
        swagger_types.update(DatavolumeInnerFields.swagger_types)

    attribute_map = {
        'shared_scopes': 'sharedScopes',
        'phase': 'phase'
    }
    if hasattr(DatavolumeInnerFields, "attribute_map"):
        attribute_map.update(DatavolumeInnerFields.attribute_map)

    def __init__(self, shared_scopes=None, phase=None, *args, **kwargs):  # noqa: E501
        """DatavolumeInternal - a model defined in Swagger"""  # noqa: E501
        self._shared_scopes = None
        self._phase = None
        self.discriminator = None
        if shared_scopes is not None:
            self.shared_scopes = shared_scopes
        if phase is not None:
            self.phase = phase
        DatavolumeInnerFields.__init__(self, *args, **kwargs)

    @property
    def shared_scopes(self):
        """Gets the shared_scopes of this DatavolumeInternal.  # noqa: E501

        Will be returned only if the user has the required permissions to view those scopes  # noqa: E501

        :return: The shared_scopes of this DatavolumeInternal.  # noqa: E501
        :rtype: list[SharedScope]
        """
        return self._shared_scopes

    @shared_scopes.setter
    def shared_scopes(self, shared_scopes):
        """Sets the shared_scopes of this DatavolumeInternal.

        Will be returned only if the user has the required permissions to view those scopes  # noqa: E501

        :param shared_scopes: The shared_scopes of this DatavolumeInternal.  # noqa: E501
        :type: list[SharedScope]
        """

        self._shared_scopes = shared_scopes

    @property
    def phase(self):
        """Gets the phase of this DatavolumeInternal.  # noqa: E501


        :return: The phase of this DatavolumeInternal.  # noqa: E501
        :rtype: DatavolumePhase
        """
        return self._phase

    @phase.setter
    def phase(self, phase):
        """Sets the phase of this DatavolumeInternal.


        :param phase: The phase of this DatavolumeInternal.  # noqa: E501
        :type: DatavolumePhase
        """

        self._phase = phase

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatavolumeInternal, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatavolumeInternal):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
