# coding: utf-8

"""
    Runai API

    # Introduction  The Run:AI Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create an **Application** through the Run:ai user interface. To create an application, in your UI, go to `Settings & Tools`, `Application` and create a new Application.  After you have created a new application, you will need to assign it access rules. To assign access rules to the application, see [Create access rules](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#create-or-delete-rules). Make sure you assign the correct rules to your application. Use the [Roles](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://docs.run.ai/latest/developer/rest-auth/#request-an-api-token).   # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PodTemplate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'containers': 'list[Container]',
        'resource_request': 'dict(str, float)'
    }

    attribute_map = {
        'containers': 'containers',
        'resource_request': 'resourceRequest'
    }

    def __init__(self, containers=None, resource_request=None):  # noqa: E501
        """PodTemplate - a model defined in Swagger"""  # noqa: E501
        self._containers = None
        self._resource_request = None
        self.discriminator = None
        self.containers = containers
        self.resource_request = resource_request

    @property
    def containers(self):
        """Gets the containers of this PodTemplate.  # noqa: E501


        :return: The containers of this PodTemplate.  # noqa: E501
        :rtype: list[Container]
        """
        return self._containers

    @containers.setter
    def containers(self, containers):
        """Sets the containers of this PodTemplate.


        :param containers: The containers of this PodTemplate.  # noqa: E501
        :type: list[Container]
        """
        if containers is None:
            raise ValueError("Invalid value for `containers`, must not be `None`")  # noqa: E501

        self._containers = containers

    @property
    def resource_request(self):
        """Gets the resource_request of this PodTemplate.  # noqa: E501


        :return: The resource_request of this PodTemplate.  # noqa: E501
        :rtype: dict(str, float)
        """
        return self._resource_request

    @resource_request.setter
    def resource_request(self, resource_request):
        """Sets the resource_request of this PodTemplate.


        :param resource_request: The resource_request of this PodTemplate.  # noqa: E501
        :type: dict(str, float)
        """
        if resource_request is None:
            raise ValueError("Invalid value for `resource_request`, must not be `None`")  # noqa: E501

        self._resource_request = resource_request

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PodTemplate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PodTemplate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
