# coding: utf-8

"""
    Runai API

    # Introduction  The Run:AI Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create an **Application** through the Run:ai user interface. To create an application, in your UI, go to `Settings & Tools`, `Application` and create a new Application.  After you have created a new application, you will need to assign it access rules. To assign access rules to the application, see [Create access rules](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#create-or-delete-rules). Make sure you assign the correct rules to your application. Use the [Roles](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://docs.run.ai/latest/developer/rest-auth/#request-an-api-token).   # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProbeRules(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'initial_delay_seconds': 'IntegerRules',
        'period_seconds': 'IntegerRules',
        'timeout_seconds': 'IntegerRules',
        'success_threshold': 'IntegerRules',
        'failure_threshold': 'IntegerRules',
        'handler': 'ProbeHandlerRules'
    }

    attribute_map = {
        'initial_delay_seconds': 'initialDelaySeconds',
        'period_seconds': 'periodSeconds',
        'timeout_seconds': 'timeoutSeconds',
        'success_threshold': 'successThreshold',
        'failure_threshold': 'failureThreshold',
        'handler': 'handler'
    }

    def __init__(self, initial_delay_seconds=None, period_seconds=None, timeout_seconds=None, success_threshold=None, failure_threshold=None, handler=None):  # noqa: E501
        """ProbeRules - a model defined in Swagger"""  # noqa: E501
        self._initial_delay_seconds = None
        self._period_seconds = None
        self._timeout_seconds = None
        self._success_threshold = None
        self._failure_threshold = None
        self._handler = None
        self.discriminator = None
        if initial_delay_seconds is not None:
            self.initial_delay_seconds = initial_delay_seconds
        if period_seconds is not None:
            self.period_seconds = period_seconds
        if timeout_seconds is not None:
            self.timeout_seconds = timeout_seconds
        if success_threshold is not None:
            self.success_threshold = success_threshold
        if failure_threshold is not None:
            self.failure_threshold = failure_threshold
        if handler is not None:
            self.handler = handler

    @property
    def initial_delay_seconds(self):
        """Gets the initial_delay_seconds of this ProbeRules.  # noqa: E501


        :return: The initial_delay_seconds of this ProbeRules.  # noqa: E501
        :rtype: IntegerRules
        """
        return self._initial_delay_seconds

    @initial_delay_seconds.setter
    def initial_delay_seconds(self, initial_delay_seconds):
        """Sets the initial_delay_seconds of this ProbeRules.


        :param initial_delay_seconds: The initial_delay_seconds of this ProbeRules.  # noqa: E501
        :type: IntegerRules
        """

        self._initial_delay_seconds = initial_delay_seconds

    @property
    def period_seconds(self):
        """Gets the period_seconds of this ProbeRules.  # noqa: E501


        :return: The period_seconds of this ProbeRules.  # noqa: E501
        :rtype: IntegerRules
        """
        return self._period_seconds

    @period_seconds.setter
    def period_seconds(self, period_seconds):
        """Sets the period_seconds of this ProbeRules.


        :param period_seconds: The period_seconds of this ProbeRules.  # noqa: E501
        :type: IntegerRules
        """

        self._period_seconds = period_seconds

    @property
    def timeout_seconds(self):
        """Gets the timeout_seconds of this ProbeRules.  # noqa: E501


        :return: The timeout_seconds of this ProbeRules.  # noqa: E501
        :rtype: IntegerRules
        """
        return self._timeout_seconds

    @timeout_seconds.setter
    def timeout_seconds(self, timeout_seconds):
        """Sets the timeout_seconds of this ProbeRules.


        :param timeout_seconds: The timeout_seconds of this ProbeRules.  # noqa: E501
        :type: IntegerRules
        """

        self._timeout_seconds = timeout_seconds

    @property
    def success_threshold(self):
        """Gets the success_threshold of this ProbeRules.  # noqa: E501


        :return: The success_threshold of this ProbeRules.  # noqa: E501
        :rtype: IntegerRules
        """
        return self._success_threshold

    @success_threshold.setter
    def success_threshold(self, success_threshold):
        """Sets the success_threshold of this ProbeRules.


        :param success_threshold: The success_threshold of this ProbeRules.  # noqa: E501
        :type: IntegerRules
        """

        self._success_threshold = success_threshold

    @property
    def failure_threshold(self):
        """Gets the failure_threshold of this ProbeRules.  # noqa: E501


        :return: The failure_threshold of this ProbeRules.  # noqa: E501
        :rtype: IntegerRules
        """
        return self._failure_threshold

    @failure_threshold.setter
    def failure_threshold(self, failure_threshold):
        """Sets the failure_threshold of this ProbeRules.


        :param failure_threshold: The failure_threshold of this ProbeRules.  # noqa: E501
        :type: IntegerRules
        """

        self._failure_threshold = failure_threshold

    @property
    def handler(self):
        """Gets the handler of this ProbeRules.  # noqa: E501


        :return: The handler of this ProbeRules.  # noqa: E501
        :rtype: ProbeHandlerRules
        """
        return self._handler

    @handler.setter
    def handler(self, handler):
        """Sets the handler of this ProbeRules.


        :param handler: The handler of this ProbeRules.  # noqa: E501
        :type: ProbeHandlerRules
        """

        self._handler = handler

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProbeRules, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProbeRules):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
