# coding: utf-8

"""
    Runai API

    # Introduction  The Run:AI Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create an **Application** through the Run:ai user interface. To create an application, in your UI, go to `Settings & Tools`, `Application` and create a new Application.  After you have created a new application, you will need to assign it access rules. To assign access rules to the application, see [Create access rules](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#create-or-delete-rules). Make sure you assign the correct rules to your application. Use the [Roles](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://docs.run.ai/latest/developer/rest-auth/#request-an-api-token).   # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectV1ResponseCommonFieldsPermissions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'users': 'list[str]',
        'groups': 'list[str]',
        'applications': 'list[str]'
    }

    attribute_map = {
        'users': 'users',
        'groups': 'groups',
        'applications': 'applications'
    }

    def __init__(self, users=None, groups=None, applications=None):  # noqa: E501
        """ProjectV1ResponseCommonFieldsPermissions - a model defined in Swagger"""  # noqa: E501
        self._users = None
        self._groups = None
        self._applications = None
        self.discriminator = None
        self.users = users
        self.groups = groups
        if applications is not None:
            self.applications = applications

    @property
    def users(self):
        """Gets the users of this ProjectV1ResponseCommonFieldsPermissions.  # noqa: E501

        Names of users that have permissions to the project.  # noqa: E501

        :return: The users of this ProjectV1ResponseCommonFieldsPermissions.  # noqa: E501
        :rtype: list[str]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this ProjectV1ResponseCommonFieldsPermissions.

        Names of users that have permissions to the project.  # noqa: E501

        :param users: The users of this ProjectV1ResponseCommonFieldsPermissions.  # noqa: E501
        :type: list[str]
        """
        if users is None:
            raise ValueError("Invalid value for `users`, must not be `None`")  # noqa: E501

        self._users = users

    @property
    def groups(self):
        """Gets the groups of this ProjectV1ResponseCommonFieldsPermissions.  # noqa: E501

        Names of groups that have permissions to the project.  # noqa: E501

        :return: The groups of this ProjectV1ResponseCommonFieldsPermissions.  # noqa: E501
        :rtype: list[str]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this ProjectV1ResponseCommonFieldsPermissions.

        Names of groups that have permissions to the project.  # noqa: E501

        :param groups: The groups of this ProjectV1ResponseCommonFieldsPermissions.  # noqa: E501
        :type: list[str]
        """
        if groups is None:
            raise ValueError("Invalid value for `groups`, must not be `None`")  # noqa: E501

        self._groups = groups

    @property
    def applications(self):
        """Gets the applications of this ProjectV1ResponseCommonFieldsPermissions.  # noqa: E501

        Names of applications that have permissions to the project.  # noqa: E501

        :return: The applications of this ProjectV1ResponseCommonFieldsPermissions.  # noqa: E501
        :rtype: list[str]
        """
        return self._applications

    @applications.setter
    def applications(self, applications):
        """Sets the applications of this ProjectV1ResponseCommonFieldsPermissions.

        Names of applications that have permissions to the project.  # noqa: E501

        :param applications: The applications of this ProjectV1ResponseCommonFieldsPermissions.  # noqa: E501
        :type: list[str]
        """

        self._applications = applications

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectV1ResponseCommonFieldsPermissions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectV1ResponseCommonFieldsPermissions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
