# coding: utf-8

"""
    Runai API

    # Introduction  The Run:AI Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create an **Application** through the Run:ai user interface. To create an application, in your UI, go to `Settings & Tools`, `Application` and create a new Application.  After you have created a new application, you will need to assign it access rules. To assign access rules to the application, see [Create access rules](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#create-or-delete-rules). Make sure you assign the correct rules to your application. Use the [Roles](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://docs.run.ai/latest/developer/rest-auth/#request-an-api-token).   # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RegistrySpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'credential_kind': 'CredentialKind',
        'user': 'str',
        'password': 'str'
    }

    attribute_map = {
        'url': 'url',
        'credential_kind': 'credentialKind',
        'user': 'user',
        'password': 'password'
    }

    def __init__(self, url=None, credential_kind=None, user=None, password=None):  # noqa: E501
        """RegistrySpec - a model defined in Swagger"""  # noqa: E501
        self._url = None
        self._credential_kind = None
        self._user = None
        self._password = None
        self.discriminator = None
        self.url = url
        self.credential_kind = credential_kind
        self.user = user
        self.password = password

    @property
    def url(self):
        """Gets the url of this RegistrySpec.  # noqa: E501

        The registry base url.  # noqa: E501

        :return: The url of this RegistrySpec.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this RegistrySpec.

        The registry base url.  # noqa: E501

        :param url: The url of this RegistrySpec.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def credential_kind(self):
        """Gets the credential_kind of this RegistrySpec.  # noqa: E501


        :return: The credential_kind of this RegistrySpec.  # noqa: E501
        :rtype: CredentialKind
        """
        return self._credential_kind

    @credential_kind.setter
    def credential_kind(self, credential_kind):
        """Sets the credential_kind of this RegistrySpec.


        :param credential_kind: The credential_kind of this RegistrySpec.  # noqa: E501
        :type: CredentialKind
        """
        if credential_kind is None:
            raise ValueError("Invalid value for `credential_kind`, must not be `None`")  # noqa: E501

        self._credential_kind = credential_kind

    @property
    def user(self):
        """Gets the user of this RegistrySpec.  # noqa: E501

        The name of the user.  # noqa: E501

        :return: The user of this RegistrySpec.  # noqa: E501
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this RegistrySpec.

        The name of the user.  # noqa: E501

        :param user: The user of this RegistrySpec.  # noqa: E501
        :type: str
        """
        if user is None:
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user

    @property
    def password(self):
        """Gets the password of this RegistrySpec.  # noqa: E501

        The password.  # noqa: E501

        :return: The password of this RegistrySpec.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this RegistrySpec.

        The password.  # noqa: E501

        :param password: The password of this RegistrySpec.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RegistrySpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegistrySpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
