# coding: utf-8

"""
    Runai API

    # Introduction  The Run:AI Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create an **Application** through the Run:ai user interface. To create an application, in your UI, go to `Settings & Tools`, `Application` and create a new Application.  After you have created a new application, you will need to assign it access rules. To assign access rules to the application, see [Create access rules](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#create-or-delete-rules). Make sure you assign the correct rules to your application. Use the [Roles](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://docs.run.ai/latest/developer/rest-auth/#request-an-api-token).   # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TokenRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'grant_type': 'str',
        'app_id': 'str',
        'app_secret': 'str',
        'code': 'str',
        'redirect_uri': 'str',
        'refresh_token': 'str',
        'username': 'str',
        'password': 'str',
        'client_id': 'str'
    }

    attribute_map = {
        'grant_type': 'grantType',
        'app_id': 'appID',
        'app_secret': 'appSecret',
        'code': 'code',
        'redirect_uri': 'redirectUri',
        'refresh_token': 'refreshToken',
        'username': 'username',
        'password': 'password',
        'client_id': 'clientID'
    }

    def __init__(self, grant_type=None, app_id=None, app_secret=None, code=None, redirect_uri=None, refresh_token=None, username=None, password=None, client_id=None):  # noqa: E501
        """TokenRequest - a model defined in Swagger"""  # noqa: E501
        self._grant_type = None
        self._app_id = None
        self._app_secret = None
        self._code = None
        self._redirect_uri = None
        self._refresh_token = None
        self._username = None
        self._password = None
        self._client_id = None
        self.discriminator = None
        if grant_type is not None:
            self.grant_type = grant_type
        if app_id is not None:
            self.app_id = app_id
        if app_secret is not None:
            self.app_secret = app_secret
        if code is not None:
            self.code = code
        if redirect_uri is not None:
            self.redirect_uri = redirect_uri
        if refresh_token is not None:
            self.refresh_token = refresh_token
        if username is not None:
            self.username = username
        if password is not None:
            self.password = password
        if client_id is not None:
            self.client_id = client_id

    @property
    def grant_type(self):
        """Gets the grant_type of this TokenRequest.  # noqa: E501


        :return: The grant_type of this TokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._grant_type

    @grant_type.setter
    def grant_type(self, grant_type):
        """Sets the grant_type of this TokenRequest.


        :param grant_type: The grant_type of this TokenRequest.  # noqa: E501
        :type: str
        """

        self._grant_type = grant_type

    @property
    def app_id(self):
        """Gets the app_id of this TokenRequest.  # noqa: E501


        :return: The app_id of this TokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._app_id

    @app_id.setter
    def app_id(self, app_id):
        """Sets the app_id of this TokenRequest.


        :param app_id: The app_id of this TokenRequest.  # noqa: E501
        :type: str
        """

        self._app_id = app_id

    @property
    def app_secret(self):
        """Gets the app_secret of this TokenRequest.  # noqa: E501


        :return: The app_secret of this TokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._app_secret

    @app_secret.setter
    def app_secret(self, app_secret):
        """Sets the app_secret of this TokenRequest.


        :param app_secret: The app_secret of this TokenRequest.  # noqa: E501
        :type: str
        """

        self._app_secret = app_secret

    @property
    def code(self):
        """Gets the code of this TokenRequest.  # noqa: E501


        :return: The code of this TokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this TokenRequest.


        :param code: The code of this TokenRequest.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def redirect_uri(self):
        """Gets the redirect_uri of this TokenRequest.  # noqa: E501


        :return: The redirect_uri of this TokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._redirect_uri

    @redirect_uri.setter
    def redirect_uri(self, redirect_uri):
        """Sets the redirect_uri of this TokenRequest.


        :param redirect_uri: The redirect_uri of this TokenRequest.  # noqa: E501
        :type: str
        """

        self._redirect_uri = redirect_uri

    @property
    def refresh_token(self):
        """Gets the refresh_token of this TokenRequest.  # noqa: E501


        :return: The refresh_token of this TokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token):
        """Sets the refresh_token of this TokenRequest.


        :param refresh_token: The refresh_token of this TokenRequest.  # noqa: E501
        :type: str
        """

        self._refresh_token = refresh_token

    @property
    def username(self):
        """Gets the username of this TokenRequest.  # noqa: E501


        :return: The username of this TokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this TokenRequest.


        :param username: The username of this TokenRequest.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def password(self):
        """Gets the password of this TokenRequest.  # noqa: E501


        :return: The password of this TokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this TokenRequest.


        :param password: The password of this TokenRequest.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def client_id(self):
        """Gets the client_id of this TokenRequest.  # noqa: E501


        :return: The client_id of this TokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this TokenRequest.


        :param client_id: The client_id of this TokenRequest.  # noqa: E501
        :type: str
        """

        self._client_id = client_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TokenRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokenRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
