# coding: utf-8

"""
    Runai API

    # Introduction  The Run:AI Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create an **Application** through the Run:ai user interface. To create an application, in your UI, go to `Settings & Tools`, `Application` and create a new Application.  After you have created a new application, you will need to assign it access rules. To assign access rules to the application, see [Create access rules](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#create-or-delete-rules). Make sure you assign the correct rules to your application. Use the [Roles](https://docs.run.ai/latest/admin/runai-setup/access-control/rbac/?h=create+delete+app#roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://docs.run.ai/latest/developer/rest-auth/#request-an-api-token).   # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Version(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sdk_version': 'str',
        'cp_version': 'str',
        'need_upgrade': 'bool'
    }

    attribute_map = {
        'sdk_version': 'sdkVersion',
        'cp_version': 'cpVersion',
        'need_upgrade': 'needUpgrade'
    }

    def __init__(self, sdk_version=None, cp_version=None, need_upgrade=False):  # noqa: E501
        """Version - a model defined in Swagger"""  # noqa: E501
        self._sdk_version = None
        self._cp_version = None
        self._need_upgrade = None
        self.discriminator = None
        self.sdk_version = sdk_version
        self.cp_version = cp_version
        self.need_upgrade = need_upgrade

    @property
    def sdk_version(self):
        """Gets the sdk_version of this Version.  # noqa: E501

        The version of the CLI SDK  # noqa: E501

        :return: The sdk_version of this Version.  # noqa: E501
        :rtype: str
        """
        return self._sdk_version

    @sdk_version.setter
    def sdk_version(self, sdk_version):
        """Sets the sdk_version of this Version.

        The version of the CLI SDK  # noqa: E501

        :param sdk_version: The sdk_version of this Version.  # noqa: E501
        :type: str
        """
        if sdk_version is None:
            raise ValueError("Invalid value for `sdk_version`, must not be `None`")  # noqa: E501

        self._sdk_version = sdk_version

    @property
    def cp_version(self):
        """Gets the cp_version of this Version.  # noqa: E501

        The version of the CP  # noqa: E501

        :return: The cp_version of this Version.  # noqa: E501
        :rtype: str
        """
        return self._cp_version

    @cp_version.setter
    def cp_version(self, cp_version):
        """Sets the cp_version of this Version.

        The version of the CP  # noqa: E501

        :param cp_version: The cp_version of this Version.  # noqa: E501
        :type: str
        """
        if cp_version is None:
            raise ValueError("Invalid value for `cp_version`, must not be `None`")  # noqa: E501

        self._cp_version = cp_version

    @property
    def need_upgrade(self):
        """Gets the need_upgrade of this Version.  # noqa: E501

        Whether the CLI needs to be upgraded  # noqa: E501

        :return: The need_upgrade of this Version.  # noqa: E501
        :rtype: bool
        """
        return self._need_upgrade

    @need_upgrade.setter
    def need_upgrade(self, need_upgrade):
        """Sets the need_upgrade of this Version.

        Whether the CLI needs to be upgraded  # noqa: E501

        :param need_upgrade: The need_upgrade of this Version.  # noqa: E501
        :type: bool
        """
        if need_upgrade is None:
            raise ValueError("Invalid value for `need_upgrade`, must not be `None`")  # noqa: E501

        self._need_upgrade = need_upgrade

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Version, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Version):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
